# Generated by Django 5.0.3 on 2024-05-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_location_job_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Industry',
            new_name='industry',
        ),
    ]
