# Generated by Django 5.0.3 on 2024-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_number',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
