# Generated by Django 5.0.3 on 2024-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_objectives',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.TextField(default=True),
        ),
    ]
